import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "@/components/elements/navbar";

const Poppins = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
});

const PoppinsBold = localFont({
  src: "./fonts/Poppins-Bold.ttf",
  variable: "--font-poppins-bold",
});

const PoppinsSemiBold = localFont({
  src: "./fonts/Poppins-SemiBold.ttf",
  variable: "--font-poppins-semibold",
});

const PoppinsMedium = localFont({
  src: "./fonts/Poppins-Medium.ttf",
  variable: "--font-poppins-medium",
});

const PoppinsLight = localFont({
  src: "./fonts/Poppins-Light.ttf",
  variable: "--font-poppins-light",
});

const PoppinsThin = localFont({
  src: "./fonts/Poppins-Thin.ttf",
  variable: "--font-poppins-thin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Poppins.variable} ${PoppinsBold.variable} ${PoppinsSemiBold.variable} ${PoppinsMedium.variable} ${PoppinsLight.variable} ${PoppinsThin.variable} antialiased`}
      >
        <header>
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
